version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    env_file: ./gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - ./gateway:/app
      # - /app/node_modules
    restart: always
